version: '3.8'

services:
  pyfinder:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    volumes:
      #- ./data:/app/data  
      - ./queries:/app/queries
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - HOST=0.0.0.0
      - PORT=5006
      - BOKEH_ALLOW_WS_ORIGIN=localhost:5006,0.0.0.0:5006,127.0.0.1:5006
      - BOKEH_WEBSOCKET_MAX_MESSAGE_SIZE=20971520
      - POSTGRES_HOST=${POSTGRES_HOST:-localhost}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-circles}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5006"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pyfinder-network

networks:
  pyfinder-network:
    driver: bridge