name: pyfinder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.2.2
  - panel=1.5.2
  - bokeh=3.6.0
  - matplotlib=3.9.2
  - sqlalchemy=2.0.34
  - param=2.1.1
  - python-dotenv=0.21.0
  - networkx=3.3
  - dask
  - dask-core
  - graph-tool
  - pytest
  - pytest-benchmark
  - pip
  - pip:
    - ortools==9.11.4210
    - psycopg2-binary==2.9.10